<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_guestbook"
 *
 * Auto generated by Extension Builder 2018-06-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => '[NITSAN] Guestbook',
	'description' => 'One of the only TYPO3 extension which provides to integrate all the features of Guestbook like review form with send mail, list of guest. Know more from extension manual.',
	'category' => 'plugin',
	'author' => 'T3:Milan Rathod, T3:Keval Pandya, FE:Mehul Nimavat, QA:Siddharth Sheth',
	'author_email' => 'sanjay@nitsan.in',
	'author_company' => 'NITSAN Technologies Pvt Ltd',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-9.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
